config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,    only: [:new, :create, :destroy]
  resources :microposts,  only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/search',  to: 'microposts#index',     via: 'get'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :content, presence: true, length: { maximum: 140 }
	validates :user_id, presence: true

  # Returns microposts from the users being followed by the given user.
  def self.from_users_followed_by(user)
  	followed_user_ids = "SELECT followed_id FROM relationships
    WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", user_id: user.id)
  end

  searchable do
    text :content
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user,  only: [:create, :destroy]
  before_action :correct_user,    only: :destroy

  def index
    if params[:search]
      @search = Micropost.search do
        fulltext params[:search]
        paginate(:page => params[:page], :per_page => 30)
      end

      @microposts = @search.results
      @count = @search.total
    else
      @microposts = [] # Micropost.paginate(page: params[:page])
      @count = @microposts.count
    end
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_item = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end

end

app/views/microposts/_micropost.html.erb
<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %>
    <%= link_to "delete", micropost,  method: :delete,
                                    data: { confirm: "You sure?" },
                                    title: micropost.content %>
  <% end %>
</li>

app/views/microposts/_search_form.html.erb
<%= form_tag(microposts_url, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Input key words" %>
  <%= submit_tag "Search", :class => "btn" %>
<% end %>

app/views/microposts/index.html.erb
<% provide(:title, 'Search microposts') %>
<h1>Search microposts</h1>
<div class="row">
  <aside class="col-xs-4">
    <h3>Content:</h3>
    <section>
      <%= render 'search_form' %>
    </section>
  </aside>
  <div class="col-xs-8">
    <ul class="microposts" id="result">
      <% if @microposts.present? %>
        <h3><%= pluralize(@count, "micropost") %> found</h3>
        <%= will_paginate %>
        <%= render @microposts, size: 52 %>
        <%= will_paginate %>
      <% else %>
        <h3>No microposts containing words <%= params[:search] %></h3>
      <% end %>
    </ul>
  </div>
</div>

<script type="text/javascript">
  document.getElementById("result").onclick = function() {
      // searchHighlight("result", "search");
      setTimeout("highlight('search')", 200);
    };
    window.onload = function() {
      // searchHighlight("result", "search");
      highlight("search");
    }
</script>